#!/bin/bash

export nmPath=$BUILD_SOURCESDIRECTORY/NSMB_RNG_WebApp/ClientApp/node_modules

cleanup() {
	echo "Pipeline cleanup"
	mv $nmPath $PIPELINE_WORKSPACE/node_modules &> /dev/null
}
run() {
	# Run a command and exit on non-zero exit codes.
	$@
	code=$?
	if [ $code != 0 ]; then
		cleanup
		echo "##vso[task.logissue type=error] Error running $1"
		exit $code
	fi
}
export -f cleanup
export -f run

echo "Pipeline init"
# This might fail due to node_modules not being in the pipeline workspace. That's OK.
mv $PIPELINE_WORKSPACE/node_modules $nmPath &> /dev/null

deploy

cleanup