trigger:
- main

pool:
  name: Default

variables:
  solution: 'NSMB_RNG.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'AzureRelease'
  targetFramework: 'net6.0'
  # Place NuGet packages outside source directory so they persist between builds.
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nugetPackages

jobs:
- job:
  displayName: BuildAndPublish
  steps:
  - task: Bash@3
    inputs:
      filePath: 'NSMB_RNG_WebApp/pipeline'
      